### ISSUE TITLE
[pin] Znki-ui general roadmap

### ISSUE THREAD

**Issue by zcharym** [Zach-Ma/Znki-ui#1]
## processing
- [x] basic login
- [x] basic note-taking function
- [ ] data-visualization(e.g. heatmap, charts)
- [x] add znki core functions(forgetting curve)
- [ ] template rendering (`latex`,`markdown`,`html`) with `html-react-parser`
- [ ] notifications
## pending
- [x] replace card accordion list with table component
- [x] add illustration
- [ ] signup page integration with login page
- [ ] animation
- [ ] redux refactor
- [ ] PWA
---
## reference
- [illustration](https://undraw.co/illustrations)
